[package]
name = "microlp"
version = "0.2.2"
authors = [
    "Alexey Zatelepin <alex.zatelepin@gmail.com>",
    "Specy <specy.dev@gmai.com"
]
edition = "2018"
license = "Apache-2.0"
description = "A fast linear programming solver library."
repository = "https://github.com/ztlpn/minilp/"
readme = "README.md"
keywords = ["linear-programming", "optimization"]
categories = ["mathematics", "science"]


[profile.release]
debug = true